<?php namespace Hewison\Inflection\Noun;

class Rules
{
    const UNCOUNTABLE = [
        'abdomen',
        'access',
        'accommodation',
        'adulthood',
        'advertising',
        'advice',
        'advise',
        'aggression',
        'aid',
        'air',
        'alcohol',
        'anger',
        'applause',
        'arithmetic',
        'asbestos',
        'assistance',
        'athletics',
        'attention',
        'bacon',
        'baggage',
        'ballet',
        'barracks',
        'beauty',
        'beer',
        'bias',
        'biology',
        'bison',
        'blood',
        'blues',
        'botany',
        'bread',
        'business',
        'butter',
        'calm',
        'carbon',
        'cardboard',
        'cash',
        'chalk',
        'chaos',
        'cheese',
        'chess',
        'childhood',
        'coal',
        'commerce',
        'compassion',
        'comprehension',
        'content',
        'corruption',
        'cotton',
        'countable',
        'courage',
        'dancing',
        'danger',
        'darkness',
        'deer',
        'dessert',
        'determination',
        'dignity',
        'dirt',
        'dust',
        'economics',
        'education',
        'electricity',
        'employment',
        'engineering',
        'enjoyment',
        'enthusiasm',
        'envy',
        'ethics',
        'evidence',
        'evolution',
        'faith',
        'fame',
        'fiction',
        'fire',
        'fish',
        'flour',
        'flu',
        'food',
        'freedom',
        'fruit',
        'fuel',
        'fun',
        'furniture',
        'gallows',
        'garbage',
        'garlic',
        'gas',
        'genetics',
        'glass',
        'gold',
        'golf',
        'gossip',
        'grammar',
        'grass',
        'gratitude',
        'grief',
        'guilt',
        'gymnastics',
        'hair',
        'halibut',
        'happiness',
        'hardware',
        'harm',
        'hate',
        'hatred',
        'health',
        'heat',
        'height',
        'help',
        'homework',
        'honesty',
        'honey',
        'hospitality ',
        'hospitality',
        'housework',
        'humor',
        'humour',
        'hunger',
        'hydrogen',
        'ice-cream',
        'ice',
        'imagination',
        'importance',
        'inflation',
        'information',
        'injustice',
        'innocence',
        'intelligence',
        'iron',
        'irony',
        'jealousy',
        'jelly',
        'joy',
        'judo',
        'juice',
        'karate',
        'kindness',
        'knowledge',
        'lack',
        'laughter',
        'lava',
        'leather',
        'leisure',
        'lightning',
        'linguistics',
        'literature',
        'litter',
        'logic',
        'loneliness',
        'love',
        'luck',
        'luggage',
        'machinery',
        'magic',
        'mail',
        'management',
        'mankind',
        'mathematics',
        'mayonnaise',
        'means',
        'measles',
        'meat',
        'methane',
        'milk',
        'money',
        'moose',
        'motherhood',
        'motivation',
        'mud',
        'music',
        'nature',
        'news',
        'nitrogen',
        'nonsense',
        'nurture',
        'nutrition',
        'obedience',
        'obesity',
        'offspring',
        'oil',
        'oxygen',
        'pasta',
        'patience',
        'physics',
        'poetry',
        'pollution',
        'pride',
        'progress',
        'psychology',
        'quartz',
        'racism',
        'rain',
        'relaxation',
        'reliability',
        'respect',
        'revenge',
        'rice',
        'rubbish',
        'rum',
        'safety',
        'salmon',
        'salt',
        'samurai',
        'sand',
        'satire',
        'scenery',
        'scissors',
        'seafood',
        'seaside',
        'semen',
        'series',
        'shame',
        'sheep',
        'shopping',
        'shrimp',
        'silence',
        'sleep',
        'smoke',
        'smoking',
        'snow',
        'soap',
        'software',
        'soil',
        'soup',
        'species',
        'speed',
        'steam',
        'stress',
        'stuff',
        'stupidity',
        'success',
        'sugar',
        'sunshine',
        'swine',
        'symmetry',
        'tea',
        'tennis',
        'texas',
        'thirst',
        'thunder',
        'timber',
        'time',
        'toast',
        'tolerance',
        'traffic',
        'travel',
        'trout',
        'trust',
        'tuna',
        'understanding',
        'underwear',
        'unemployment',
        'unity',
        'usage',
        'validity',
        'veal',
        'vegetarianism',
        'vegetation',
        'vengeance',
        'violence',
        'vitality',
        'warmth',
        'water',
        'wealth',
        'weather',
        'welfare',
        'wheat',
        'whiskey',
        'width',
        'wildlife',
        'wine',
        'wisdom',
        'wood',
        'wool',
        'work',
        'yeast',
        'yoga',
        'youth',
        'zinc',
        'zoology'
    ];
    
    const SINGULAR_TO_PLURAL = [
        "abacus" => ["abacuses"],
        "abyss" => ["abysses"],
        "addendum" => ["addenda"],
        "agenda" => ["agendas"],
        "agendum" => ["agenda"],
        "agent-provocateur" => ["agents-provocateurs"],
        "aide-de-camp" => ["aides-de-camp"],
        "aircraft" => ["aircraft"],
        "albino" => ["albinos"],
        "album" => ["albums"],
        "alfalfa" => ["alfalfas"],
        "alga" => ["algae"],
        "alumna" => ["alumnae"],
        "alumnus" => ["alumni"],
        "amoeba" => ["amoebae"],
        "analysis" => ["analyses"],
        "anathema" => ["anathemata"],
        "annex" => ["annexes"],
        "antenna" => ["antennas"],
        "antithesis" => ["antitheses"],
        "apex" => ["apices", "apexes"],
        "apparatus" => ["apparatuses"],
        "appendix" => ["appendices", "appendixes"],
        "apple" => ["apples"],
        "aquarium" => ["aquaria", "aquariums"],
        "arch" => ["arches"],
        "armadillo" => ["armadillos"],
        "ass" => ["asses"],
        "atlas" => ["atlases"],
        "attorne-general" => ["attorneys-general"],
        "aurora" => ["auroras"],
        "auto" => ["autos"],
        "axe" => ["axes"],
        "axis" => ["axes"],
        "baby" => ["babies"],
        "bacillus" => ["bacilli"],
        "bacterium" => ["bacteria"],
        "balloon" => ["balloons"],
        "banana" => ["bananas"],
        "barracks" => ["barracks"],
        "barracuda" => ["barracudas"],
        "basis" => ["bases"],
        "batch" => ["batches"],
        "beach" => ["beaches"],
        "beau" => ["beaux"],
        "beau-geste" => ["beaux-gestes"],
        "bel-homme" => ["beaux-hommes"],
        "belief" => ["beliefs"],
        "belle-epoque" => ["belles-epoques", "belle-epoques"],
        "bikini" => ["bikinis"],
        "bildungsroman" => ["bildungsromane"],
        "bill-of-attainder" => ["bills-of-attainder"],
        "biscotto" => ["biscotti"],
        "bon-mot" => ["bons-mots"],
        "bon-vivant" => ["bons-vivants"],
        "book" => ["books"],
        "box" => ["boxes"],
        "brother" => ["brothers"],
        "brush" => ["brushes"],
        "buffalo" => ["buffalos", "buffaloes"],
        "bureau" => ["bureaus", "bureaux"],
        "bus" => ["buses", "busses"],
        "cactus" => ["cacti"],
        "calf" => ["calves"],
        "cameo" => ["cameos"],
        "candelabrum" => ["candelabra"],
        "canto" => ["cantos"],
        "carton" => ["cartons"],
        "cat-o'-nine-tails" => ["cat-o'-nine-tails"],
        "cello" => ["cellos"],
        "chateau" => ["chateaux", "chateaus"],
        "cherry" => ["cherries"],
        "chick" => ["chicks"],
        "chicken" => ["chickens"],
        "chief" => ["chiefs"],
        "child" => ["children"],
        "church" => ["churches"],
        "château" => ["châteaux", "châteaus"],
        "circus" => ["circuses"],
        "city" => ["cities"],
        "cod" => ["cods"],
        "codex" => ["codices"],
        "combo" => ["combos"],
        "complex" => ["complexes"],
        "concerto" => ["concerti", "concertos"],
        "copy" => ["copies"],
        "cornea" => ["corneas"],
        "corps" => ["corps"],
        "corpus" => ["corpora", "corpuses"],
        "coup d'etat" => ["coups d'etat"],
        "court-martial" => ["courts-martial"],
        "cri du coeur" => ["cris du coeur"],
        "crisis" => ["crises"],
        "criterion" => ["criteria"],
        "crocus" => ["crocuses"],
        "curriculum" => ["curricula"],
        "daisy" => ["daisies"],
        "datum" => ["data"],
        "des" => ["deses"],
        "diagnosis" => ["diagnoses"],
        "dictionary" => ["dictionaries"],
        "die" => ["dice"],
        "director-general" => ["directors-general"],
        "dogma" => ["dogmata"],
        "domino" => ["dominoes"],
        "dukhobor" => ["dukhobortsy"],
        "duo" => ["duos"],
        "duplex" => ["duplexes"],
        "dwarf" => ["dwarves", "dwarfs"],
        "echo" => ["echoes"],
        "ego" => ["egos"],
        "elf" => ["elves"],
        "ellipsis" => ["ellipses"],
        "embargo" => ["embargoes"],
        "emphasis" => ["emphases"],
        "entente-cordiale" => ["ententes-cordiales"],
        "erratum" => ["errata"],
        "fait-accompli" => ["faits-accomplis"],
        "family" => ["families"],
        "faux-pas" => ["faux-pas"],
        "fax" => ["faxes"],
        "fee simple absolute" => ["fees simple absolute"],
        "fez" => ["fezzes", "fezes"],
        "fireman" => ["firemen"],
        "flush" => ["flushes"],
        "fly" => ["flies"],
        "focus" => ["foci", "focuses"],
        "folio" => ["folios"],
        "foot" => ["feet"],
        "formula" => ["formulas", "formulae"],
        "fungus" => ["fungi", "funguses"],
        "gallows" => ["gallows"],
        "gas" => ["gases"],
        "gens" => ["gentes"],
        "genu" => ["genua"],
        "genus" => ["genera"],
        "goose" => ["geese"],
        "governor-general" => ["governors-general"],
        "graffito" => ["graffiti"],
        "grief" => ["griefs"],
        "grouse" => ["grouses"],
        "gulf" => ["gulfs"],
        "guru" => ["gurus"],
        "half" => ["halves"],
        "hallux" => ["halluces"],
        "halo" => ["halos"],
        "ham on rye" => ["ham-on-ryes"],
        "handkerchief" => ["handkerchiefs"],
        "head of state" => ["heads of states", "heads of state"],
        "hero" => ["heroes"],
        "hetero" => ["heteros"],
        "hex" => ["hexes"],
        "hippopotamus" => ["hippopotami", "hippopotamuses"],
        "hoax" => ["hoaxes"],
        "holluschik" => ["holluschikie"],
        "hoof" => ["hooves"],
        "hypothesis" => ["hypotheses"],
        "idee-fixe" => ["idees-fixes"],
        "index" => ["indexes", "indices", "indeces"],
        "inferno" => ["infernos"],
        "insigne" => ["insignia"],
        "iris" => ["irises"],
        "iter" => ["itinera"],
        "jack-in-the-box" => ["jacks-in-the-box", "jack-in-the-boxes"],
        "jack-in-the-pulpit" => ["jacks-in-the-pulpit", "jack-in-the-pulpits"],
        "jack-o'-lantern" => ["jack-o'-lanterns"],
        "kerchief" => ["kerchiefs"],
        "kimono" => ["kimonos"],
        "kiss" => ["kisses"],
        "knife" => ["knives"],
        "krone" => ["kroner"],
        "lady" => ["ladies"],
        "larva" => ["larvae"],
        "lasso" => ["lassos"],
        "leaf" => ["leaves"],
        "lemma" => ["lemmata", "lemmas"],
        "libretto" => ["libretti", "librettos"],
        "life" => ["lives"],
        "loaf" => ["loaves"],
        "locus" => ["loci"],
        "louse" => ["lice"],
        "man" => ["men"],
        "man-about-town" => ["men-about-town"],
        "man-child" => ["men-children"],
        "man-of-war" => ["men-of-war"],
        "mango" => ["mangoes"],
        "manservant" => ["menservants"],
        "martini" => ["martinis"],
        "matrix" => ["matrices", "matrixes"],
        "matzo" => ["matzoth"],
        "medium" => ["media"],
        "memento" => ["mementos"],
        "memo" => ["memos"],
        "memorandum" => ["memoranda"],
        "menu" => ["menus"],
        "mess" => ["messes"],
        "millennium" => ["millenniums", "millennium", "millennia"],
        "minister-president" => ["ministers-president"],
        "minutia" => ["minutiae"],
        "mischief" => ["mischiefs"],
        "moose" => ["moose"],
        "mosquito" => ["mosquitoes"],
        "motto" => ["mottoes"],
        "mouse" => ["mice"],
        "muff" => ["muffs"],
        "mussolini" => ["mussolinis"],
        "nanny" => ["nannies"],
        "nebula" => ["nebulae", "nebulas"],
        "neurosis" => ["neuroses"],
        "never-was" => ["never-weres"],
        "nova" => ["novas"],
        "nucleus" => ["nuclei"],
        "oaf" => ["oafs"],
        "oasis" => ["oases"],
        "octopus" => ["octopuses", "octopodes", "octopi"],
        "opus" => ["opera", "operas"],
        "ornis" => ["ornithes"],
        "ovum" => ["ova"],
        "ox" => ["oxen"],
        "page" => ["pages"],
        "pakistani" => ["pakistanis"],
        "panino" => ["panini"],
        "paparazzo" => ["paparazzi"],
        "paralysis" => ["paralyses"],
        "parenthesis" => ["parentheses"],
        "party" => ["parties"],
        "pass" => ["passes"],
        "passerby" => ["passersby"],
        "penny" => ["pennies"],
        "person" => ["people"],
        "phenomenon" => ["phenomena"],
        "phobia" => ["phobias"],
        "photo" => ["photos"],
        "phylum" => ["phyla"],
        "piano" => ["pianos"],
        "pitch" => ["pitches"],
        "plateau" => ["plateaux", "plateaus"],
        "poppy" => ["poppies"],
        "portfolio" => ["portfolios"],
        "portico" => ["porticos"],
        "potato" => ["potatoes"],
        "pro" => ["pros"],
        "procurator-fiscal" => ["procurators-fiscal"],
        "prognosis" => ["prognoses"],
        "proof" => ["proofs"],
        "pupa" => ["pupae"],
        "quadrans" => ["quadrantes"],
        "quarto" => ["quartos"],
        "quiz" => ["quizzes"],
        "radius" => ["radii"],
        "referendum" => ["referenda", "referendums"],
        "reflex" => ["reflexes"],
        "rhombus" => ["rhombuses"],
        "roof" => ["roofs"],
        "rubai" => ["rubaiyat"],
        "runner-up" => ["runners-up"],
        "safe" => ["safes"],
        "salmon" => ["salmons"],
        "scarf" => ["scarves", "scarfs"],
        "schema" => ["schemata", "schemas"],
        "schoolchild" => ["schoolchildren"],
        "scratch" => ["scratches"],
        "scrotum" => ["scrota", "scrotums"],
        "self" => ["selves"],
        "seraph" => ["seraphim"],
        "sheaf" => ["sheaves"],
        "shelf" => ["shelves"],
        "ship of the line" => ["ships of the line"],
        "shrimp" => ["shrimps"],
        "shtetl" => ["shtetlach"],
        "silo" => ["silos"],
        "snafu" => ["snafus"],
        "solo" => ["solos"],
        "son of a bitch" => ["sons of bitches", "sons-of-a-bitch"],
        "son-in-law" => ["sons-in-law"],
        "spaghetto" => ["spaghettis", "spaghetti"],
        "splash" => ["splashes"],
        "spy" => ["spies"],
        "stadium" => ["stadiums"],
        "stereo" => ["stereos"],
        "stigma" => ["stigmata", "stigmas"],
        "stimulus" => ["stimuli"],
        "stitch" => ["stitches"],
        "stoma" => ["stomata", "stomas"],
        "story" => ["stories"],
        "stratum" => ["strata"],
        "studio" => ["studios"],
        "syllabus" => ["syllabi", "syllabuses"],
        "symposium" => ["symposia", "symposiums"],
        "synopsis" => ["synopses"],
        "synthesis" => ["syntheses"],
        "tableau" => ["tableaux", "tableaus"],
        "taco" => ["tacos"],
        "tattoo" => ["tattoos"],
        "tax" => ["taxes"],
        "tete-a-tete" => ["tete-a-tetes"],
        "that" => ["those"],
        "thesis" => ["theses"],
        "thief" => ["thieves"],
        "this" => ["these"],
        "tomato" => ["tomatoes"],
        "tooth" => ["teeth"],
        "tornado" => ["tornadoes"],
        "torpedo" => ["torpedoes"],
        "torte" => ["torten"],
        "tour-de-force" => ["tours-de-force"],
        "trout" => ["trouts"],
        "try" => ["tries"],
        "tuna" => ["tunas"],
        "turf" => ["turfs"],
        "tuxedo" => ["tuxedos"],
        "typo" => ["typos"],
        "ushabti" => ["ushabtiu"],
        "vas" => ["vasa"],
        "vertebra" => ["vertebrae"],
        "vertex" => ["vertices", "vertexes"],
        "veto" => ["vetoes"],
        "video" => ["videos"],
        "vita" => ["vitae"],
        "volcano" => ["volcanoes"],
        "vortex" => ["vortices", "vortexes"],
        "walrus" => ["walruses"],
        "waltz" => ["waltzes"],
        "wash" => ["washes"],
        "watch" => ["watches"],
        "wharf" => ["wharves"],
        "wife" => ["wives"],
        "will-o'-the-wisp" => ["will-o'-the-wisps"],
        "wish" => ["wishes"],
        "wolf" => ["wolves"],
        "woman" => ["women"],
        "woman-doctor" => ["women-doctors"],
        "word" => ["words"],
        "workman" => ["workmen"],
        "wunderkind" => ["wunderkinder"],
        "yemeni" => ["yemenis"],
        "yeshiva" => ["yeshivoth"],
        "yo" => ["yos"],
        "zecchino" => ["zecchini"],
        "zero" => ["zeros", "zeroes"],
        "zoo" => ["zoos"],
    ];
    
    const PLURAL_TO_SINGULAR = [
        "abacuses" => "abacus",
        "abysses" => "abyss",
        "addenda" => "addendum",
        "agendas" => "agenda",
        "agenda" => "agendum",
        "agents-provocateurs" => "agent-provocateur",
        "aides-de-camp" => "aide-de-camp",
        "aircraft" => "aircraft",
        "albinos" => "albino",
        "albums" => "album",
        "alfalfas" => "alfalfa",
        "algae" => "alga",
        "alumnae" => "alumna",
        "alumni" => "alumnus",
        "amoebae" => "amoeba",
        "analyses" => "analysis",
        "anathemata" => "anathema",
        "annexes" => "annex",
        "antennas" => "antenna",
        "antitheses" => "antithesis",
        "apices" => "apex",
        "apexes" => "apex",
        "apparatuses" => "apparatus",
        "appendices" => "appendix",
        "appendixes" => "appendix",
        "apples" => "apple",
        "aquaria" => "aquarium",
        "aquariums" => "aquarium",
        "arches" => "arch",
        "armadillos" => "armadillo",
        "asses" => "ass",
        "atlases" => "atlas",
        "attorneys-general" => "attorne-general",
        "auroras" => "aurora",
        "autos" => "auto",
        "axes" => "axis",
        "babies" => "baby",
        "bacilli" => "bacillus",
        "bacteria" => "bacterium",
        "balloons" => "balloon",
        "bananas" => "banana",
        "barracks" => "barracks",
        "barracudas" => "barracuda",
        "bases" => "basis",
        "batches" => "batch",
        "beaches" => "beach",
        "beaux" => "beau",
        "beaux-gestes" => "beau-geste",
        "beaux-hommes" => "bel-homme",
        "beliefs" => "belief",
        "belles-epoques" => "belle-epoque",
        "belle-epoques" => "belle-epoque",
        "bikinis" => "bikini",
        "bildungsromane" => "bildungsroman",
        "bills-of-attainder" => "bill-of-attainder",
        "biscotti" => "biscotto",
        "bons-mots" => "bon-mot",
        "bons-vivants" => "bon-vivant",
        "books" => "book",
        "boxes" => "box",
        "brothers" => "brother",
        "brushes" => "brush",
        "buffalos" => "buffalo",
        "buffaloes" => "buffalo",
        "bureaus" => "bureau",
        "bureaux" => "bureau",
        "buses" => "bus",
        "busses" => "bus",
        "cacti" => "cactus",
        "calves" => "calf",
        "cameos" => "cameo",
        "candelabra" => "candelabrum",
        "cantos" => "canto",
        "cartons" => "carton",
        "cat-o'-nine-tails" => "cat-o'-nine-tails",
        "cellos" => "cello",
        "chateaux" => "chateau",
        "chateaus" => "chateau",
        "cherries" => "cherry",
        "chicks" => "chick",
        "chickens" => "chicken",
        "chiefs" => "chief",
        "children" => "child",
        "churches" => "church",
        "châteaux" => "château",
        "châteaus" => "château",
        "circuses" => "circus",
        "cities" => "city",
        "cods" => "cod",
        "codices" => "codex",
        "combos" => "combo",
        "complexes" => "complex",
        "concerti" => "concerto",
        "concertos" => "concerto",
        "copies" => "copy",
        "corneas" => "cornea",
        "corps" => "corps",
        "corpora" => "corpus",
        "corpuses" => "corpus",
        "coups d'etat" => "coup d'etat",
        "courts-martial" => "court-martial",
        "cris du coeur" => "cri du coeur",
        "crises" => "crisis",
        "criteria" => "criterion",
        "crocuses" => "crocus",
        "curricula" => "curriculum",
        "daisies" => "daisy",
        "data" => "datum",
        "deses" => "des",
        "diagnoses" => "diagnosis",
        "dictionaries" => "dictionary",
        "dice" => "die",
        "directors-general" => "director-general",
        "dogmata" => "dogma",
        "dominoes" => "domino",
        "dukhobortsy" => "dukhobor",
        "duos" => "duo",
        "duplexes" => "duplex",
        "dwarves" => "dwarf",
        "dwarfs" => "dwarf",
        "echoes" => "echo",
        "egos" => "ego",
        "elves" => "elf",
        "ellipses" => "ellipsis",
        "embargoes" => "embargo",
        "emphases" => "emphasis",
        "ententes-cordiales" => "entente-cordiale",
        "errata" => "erratum",
        "faits-accomplis" => "fait-accompli",
        "families" => "family",
        "faux-pas" => "faux-pas",
        "faxes" => "fax",
        "fees simple absolute" => "fee simple absolute",
        "fezzes" => "fez",
        "fezes" => "fez",
        "firemen" => "fireman",
        "flushes" => "flush",
        "flies" => "fly",
        "foci" => "focus",
        "focuses" => "focus",
        "folios" => "folio",
        "feet" => "foot",
        "formulas" => "formula",
        "formulae" => "formula",
        "fungi" => "fungus",
        "funguses" => "fungus",
        "gallows" => "gallows",
        "gases" => "gas",
        "gentes" => "gens",
        "genua" => "genu",
        "genera" => "genus",
        "geese" => "goose",
        "governors-general" => "governor-general",
        "graffiti" => "graffito",
        "griefs" => "grief",
        "grouses" => "grouse",
        "gulfs" => "gulf",
        "gurus" => "guru",
        "halves" => "half",
        "halluces" => "hallux",
        "halos" => "halo",
        "ham-on-ryes" => "ham on rye",
        "handkerchiefs" => "handkerchief",
        "heads of states" => "head of state",
        "heads of state" => "head of state",
        "heroes" => "hero",
        "heteros" => "hetero",
        "hexes" => "hex",
        "hippopotami" => "hippopotamus",
        "hippopotamuses" => "hippopotamus",
        "hoaxes" => "hoax",
        "holluschikie" => "holluschik",
        "hooves" => "hoof",
        "hypotheses" => "hypothesis",
        "idees-fixes" => "idee-fixe",
        "indexes" => "index",
        "indices" => "index",
        "indeces" => "index",
        "infernos" => "inferno",
        "insignia" => "insigne",
        "irises" => "iris",
        "itinera" => "iter",
        "jacks-in-the-box" => "jack-in-the-box",
        "jack-in-the-boxes" => "jack-in-the-box",
        "jacks-in-the-pulpit" => "jack-in-the-pulpit",
        "jack-in-the-pulpits" => "jack-in-the-pulpit",
        "jack-o'-lanterns" => "jack-o'-lantern",
        "kerchiefs" => "kerchief",
        "kimonos" => "kimono",
        "kisses" => "kiss",
        "knives" => "knife",
        "kroner" => "krone",
        "ladies" => "lady",
        "larvae" => "larva",
        "lassos" => "lasso",
        "leaves" => "leaf",
        "lemmata" => "lemma",
        "lemmas" => "lemma",
        "libretti" => "libretto",
        "librettos" => "libretto",
        "lives" => "life",
        "loaves" => "loaf",
        "loci" => "locus",
        "lice" => "louse",
        "men" => "man",
        "men-about-town" => "man-about-town",
        "men-children" => "man-child",
        "men-of-war" => "man-of-war",
        "mangoes" => "mango",
        "menservants" => "manservant",
        "martinis" => "martini",
        "matrices" => "matrix",
        "matrixes" => "matrix",
        "matzoth" => "matzo",
        "media" => "medium",
        "mementos" => "memento",
        "memos" => "memo",
        "memoranda" => "memorandum",
        "menus" => "menu",
        "messes" => "mess",
        "millenniums" => "millennium",
        "millennium" => "millennium",
        "millennia" => "millennium",
        "ministers-president" => "minister-president",
        "minutiae" => "minutia",
        "mischiefs" => "mischief",
        "moose" => "moose",
        "mosquitoes" => "mosquito",
        "mottoes" => "motto",
        "mice" => "mouse",
        "muffs" => "muff",
        "mussolinis" => "mussolini",
        "nannies" => "nanny",
        "nebulae" => "nebula",
        "nebulas" => "nebula",
        "neuroses" => "neurosis",
        "never-weres" => "never-was",
        "novas" => "nova",
        "nuclei" => "nucleus",
        "oafs" => "oaf",
        "oases" => "oasis",
        "octopuses" => "octopus",
        "octopodes" => "octopus",
        "octopi" => "octopus",
        "opera" => "opus",
        "operas" => "opus",
        "ornithes" => "ornis",
        "ova" => "ovum",
        "oxen" => "ox",
        "pages" => "page",
        "pakistanis" => "pakistani",
        "panini" => "panino",
        "paparazzi" => "paparazzo",
        "paralyses" => "paralysis",
        "parentheses" => "parenthesis",
        "parties" => "party",
        "passes" => "pass",
        "passersby" => "passerby",
        "pennies" => "penny",
        "people" => "person",
        "phenomena" => "phenomenon",
        "phobias" => "phobia",
        "photos" => "photo",
        "phyla" => "phylum",
        "pianos" => "piano",
        "pitches" => "pitch",
        "plateaux" => "plateau",
        "plateaus" => "plateau",
        "poppies" => "poppy",
        "portfolios" => "portfolio",
        "porticos" => "portico",
        "potatoes" => "potato",
        "pros" => "pro",
        "procurators-fiscal" => "procurator-fiscal",
        "prognoses" => "prognosis",
        "proofs" => "proof",
        "pupae" => "pupa",
        "quadrantes" => "quadrans",
        "quartos" => "quarto",
        "quizzes" => "quiz",
        "radii" => "radius",
        "referenda" => "referendum",
        "referendums" => "referendum",
        "reflexes" => "reflex",
        "rhombuses" => "rhombus",
        "roofs" => "roof",
        "rubaiyat" => "rubai",
        "runners-up" => "runner-up",
        "safes" => "safe",
        "salmons" => "salmon",
        "scarves" => "scarf",
        "scarfs" => "scarf",
        "schemata" => "schema",
        "schemas" => "schema",
        "schoolchildren" => "schoolchild",
        "scratches" => "scratch",
        "scrota" => "scrotum",
        "scrotums" => "scrotum",
        "selves" => "self",
        "seraphim" => "seraph",
        "sheaves" => "sheaf",
        "shelves" => "shelf",
        "ships of the line" => "ship of the line",
        "shrimps" => "shrimp",
        "shtetlach" => "shtetl",
        "silos" => "silo",
        "snafus" => "snafu",
        "solos" => "solo",
        "sons of bitches" => "son of a bitch",
        "sons-of-a-bitch" => "son of a bitch",
        "sons-in-law" => "son-in-law",
        "spaghettis" => "spaghetto",
        "spaghetti" => "spaghetto",
        "splashes" => "splash",
        "spies" => "spy",
        "stadiums" => "stadium",
        "stereos" => "stereo",
        "stigmata" => "stigma",
        "stigmas" => "stigma",
        "stimuli" => "stimulus",
        "stitches" => "stitch",
        "stomata" => "stoma",
        "stomas" => "stoma",
        "stories" => "story",
        "strata" => "stratum",
        "studios" => "studio",
        "syllabi" => "syllabus",
        "syllabuses" => "syllabus",
        "symposia" => "symposium",
        "symposiums" => "symposium",
        "synopses" => "synopsis",
        "syntheses" => "synthesis",
        "tableaux" => "tableau",
        "tableaus" => "tableau",
        "tacos" => "taco",
        "tattoos" => "tattoo",
        "taxes" => "tax",
        "tete-a-tetes" => "tete-a-tete",
        "those" => "that",
        "theses" => "thesis",
        "thieves" => "thief",
        "these" => "this",
        "tomatoes" => "tomato",
        "teeth" => "tooth",
        "tornadoes" => "tornado",
        "torpedoes" => "torpedo",
        "torten" => "torte",
        "tours-de-force" => "tour-de-force",
        "trouts" => "trout",
        "tries" => "try",
        "tunas" => "tuna",
        "turfs" => "turf",
        "tuxedos" => "tuxedo",
        "typos" => "typo",
        "ushabtiu" => "ushabti",
        "vasa" => "vas",
        "vertebrae" => "vertebra",
        "vertices" => "vertex",
        "vertexes" => "vertex",
        "vetoes" => "veto",
        "videos" => "video",
        "vitae" => "vita",
        "volcanoes" => "volcano",
        "vortices" => "vortex",
        "vortexes" => "vortex",
        "walruses" => "walrus",
        "waltzes" => "waltz",
        "washes" => "wash",
        "watches" => "watch",
        "wharves" => "wharf",
        "wives" => "wife",
        "will-o'-the-wisps" => "will-o'-the-wisp",
        "wishes" => "wish",
        "wolves" => "wolf",
        "women" => "woman",
        "women-doctors" => "woman-doctor",
        "words" => "word",
        "workmen" => "workman",
        "wunderkinder" => "wunderkind",
        "yemenis" => "yemeni",
        "yeshivoth" => "yeshiva",
        "yos" => "yo",
        "zecchini" => "zecchino",
        "zeros" => "zero",
        "zeroes" => "zero",
        "zoos" => "zoo",
    ];
    
    const SINGULAR_PATTERNS = [
        "/[bcdfgjkmruopquvxzw]$/",
        "/ss$/",
        "/sis$/",
        "/thos$/",
        "/pus$/",
        "/tis$/",
        "/^[a-z]{1}s$/",
        "/us$/",
        "/(n|r)is$/",
        "/tmas$/",
        "/[abefgjklpqywxyz]a$/",
        "/[^i]ca$/",
        "/[^n]da$/",
        "/[^p]ha$/",
        "/([^dvtlar])ia$/",
        "/([^i]|(cteri|at|ul|at|asi|di|nd|ov|ri))a$/",
        "/(z|h|g|b|r|l)eria$/",
        "/[^ci]teria$/",
        "/[^cb]ilia$/",
        "/[^xi]lia$/",
        "/[^e]ma$/",
        "/[^aeu]na$/",
        "/[^ciam][a-z]na$/",
        "/[ifo]\w{2}na$/",
        "/[^aip]ta$/",
        "/[^rmpe][a-z]ta$/",
        "/[^gart][a-z][a-z]ta$/",
        "/(a)e$/",
        "/people$/",
        "/[^t][^t][^o][^i][^a]e$/",
        "/[^i][^t]h$/",
        "/[uacgzheimnot][a-z]i$/",
        "/[^atvliopcbnmgfds][a-z]*i$/",
        "/[a-z][^ertiopasl][a-z]+[a-z]i$/",
        "/[^e]l$/",
        "/[^e]n$/"
    ];
    
    const PLURAL_PATTERNS = [
        "/men$/",
        "/sortia$/",
        "/^media$/",
        "/^cilia$/",
        "/abilia$/",
        "/trivia$/",
        "/[^jtma](chi*|yn|ol|am|i|umn|os|an|ermin|omb|ul|eol|cle|on|un)i$/",
        "/(um|pa|ro)ni$/",
        "/(uo|io)si$/",
        "/onchi$/",
        "/(o|u|a)li$/",
        "/(e|i)i$/",
        "/ies$/",
        "/ves$/",
        "/es$/",
        "/[aouiey]ys$/",
        "/oos$/",
        "/ios$/",
        "/[tfg]ee[sth]{1,2}e*$/",
        "/[^aouies][aoui]s$/",
        "/[ea]s$/",
        "/[^aouie]s$/",
    ];
    
    const TO_PLURAL_EXPRESSIONS = [
        // appendix, spadix, radix
        [
            "expression" => "/dix$/",
            "replacement" => 'dices'
        ],
        // pooch
        [
            "expression" => "/ooch$/",
            "replacement" => '$1chs'
        ],
        // man, policeman, fireman,
        [
            "expression" => "/(m)an$/",
            "replacement" => '$1en'
        ],
        // person
        [
            "expression" => "/(pe)rson$/",
            "replacement" => '$1ople'
        ],
        // child
        [
            "expression" => "/(child)$/",
            "replacement" => '$1ren'
        ],
        // ox
        [
            "expression" => "/^(ox)$/",
            "replacement" => '$1en'
        ],
        // axis
        [
            "expression" => "/(ax|test)is$/",
            "replacement" => '$1es'
        ],
        // fungus, locus, nucleus, radius,
        [
            "expression" => "/(op|ir|umn|am|ll|ct|oc|ng|le|di|ul|ab|rmin|or|in)us$/",
            "replacement" => '$1i'
        ],
        // status
        [
            "expression" => "/(alias|status)$/",
            "replacement" => '$1es'
        ],
        // Syllabus thrombus
        [
            "expression" => "/(bu)s$/",
            "replacement" => '$1ses'
        ],
        // buffalo, cargo, echo, embargo
        [
            "expression" => "/(fal|tat|ch|rg|ott|mat|ped|et|can|er|uit|her|ad)o$/",
            "replacement" => '$1oes'
        ],
        // bacterium, curriculum, datum, erratum,
        [
            "expression" => "/([aeiouy]ri|dat|cul|rat|nasi|edi|rand|ov)um$/",
            "replacement" => '$1a'
        ],
        // bacterium, curriculum, datum, erratum,
        [
            "expression" => "/([aoeuiy]|er)ion$/",
            "replacement" => '$1ia'
        ],
        // sherion
        [
            "expression" => "/(mat|erio|omen|hedr)on$/",
            "replacement" => '$1a'
        ],
        // analysis, basis, crisis, ellipsis, hypothesis
        [
            "expression" => "/(is|ps|hes|as|ys|os|ax)is$/",
            "replacement" => '$1es'
        ],
        // calf elf half knife
        [
            "expression" => "/(?:([^f])fe|([lrf])f)$/",
            "replacement" => '$1$2ves'
        ],
        // criterion
        [
            "expression" => "/(hive)$/",
            "replacement" => '$1s'
        ],
        // ally army baby beauty
        [
            "expression" => "/([^aeiouy]|qu)y$/",
            "replacement" => '$1ies'
        ],
        // alley attorney essay boy delay
        [
            "expression" => "/([aeiouy]y)$/",
            "replacement" => '$1s'
        ],
        // matrix vertex index
        [
            "expression" => "/(matr|vert|ind)(ix|ex)$/",
            "replacement" => '$1ices'
        ],
        // louse mouse booklouse
        [
            "expression" => "/([m|l])ouse$/",
            "replacement" => '$1ice'
        ],
        // alga, alumna, antenna, larva
        [
            "expression" => "/(alg|lumn|tenn|arv|ebul|pup|rteb|vit)a$/",
            "replacement" => '$1ae'
        ],
        // buzz fizz klutz quiz topaz waltz
        [
            "expression" => "/(uz|qui|ut)(z)$/",
            "replacement" => '$1$2zes'
        ],
        // waltz
        [
            "expression" => "/(opa|alt)(z)$/",
            "replacement" => '$1zes'
        ],
        // foot tooth
        [
            "expression" => "/^(f|t|g)oo([thse]{1,2})$/",
            "replacement" => '$1ee$2'
        ],
        // plateau
        [
            "expression" => "/([^aeiouy])eau$/",
            "replacement" => '$1eaux'
        ],
        // loaf
        [
            "expression" => "/([aeiouy])f$/",
            "replacement" => '$1ves'
        ],
        // arch atlas ax bash bench
        [
            "expression" => "/(x|ch|ss|sh|s)$/",
            "replacement" => '$1es'
        ],
        [
            "expression" => "/o$/",
            "replacement" => 'oes'
        ],
        [
            "expression" => "/$/",
            "replacement" => 's'
        ],
    ];
    
    const TO_SINGULAR_EXPRESSIONS = [
        // babies cities universities victories
        [
            "expression" => "/([^aeiouy]|qu)ies$/",
            "replacement" => '$1y'
        ],
        // buffaloes, cargoes, echoes, embargoes
        [
            "expression" => "/(falo|tato|cho|rgo|otto|mato|pedo|eto|cano|ero|uito|hero)es$/",
            "replacement" => '$1'
        ],
        // axes , paralyses
        [
            "expression" => "/(lys|xis|bas|ris|ips|thes|uros|oas|ys|ops)es$/",
            "replacement" => '$1is'
        ],
        // buzzes fizzes quizzes
        [
            "expression" => "/(z)zes$/",
            "replacement" => '$1'
        ],
        // algae, alumnae, antennae, larvae
        [
            "expression" => "/(alg|lumn|tenn|arv|ebul|pup|rteb|vit)ae$/",
            "replacement" => '$1a'
        ],
        // bacteria, curricula, data, errata,
        [
            "expression" => "/(cteri|at|ul|at|asi|di|nd|ov|ri)a$/",
            "replacement" => '$1um'
        ],
        // matrices indices
        [
            "expression" => "/(vert|ind)ices$/",
            "replacement" => '$1ex'
        ],
        // analyses synopses prognoses
        [
            "expression" => "/(()(a)naly|(b)a|(d)iagno|(p)arenthe|(p)rogno|(s)ynop|(t)he|(p)ha)ses/",
            "replacement" => '$1$2sis'
        ],
        // archive hives chives
        [
            "expression" => "/(hive)s$/",
            "replacement" => '$1'
        ],
        // adjectives creatives causatives
        [
            "expression" => "/(tive)s$/",
            "replacement" => '$1'
        ],
        // curves
        [
            "expression" => "/(curve)s$/",
            "replacement" => '$1'
        ],
        // attorneys
        [
            "expression" => "/([aeiou]y)s$/",
            "replacement" => '$1'
        ],
        // louse mouse booklouse
        [
            "expression" => "/([m|l])ice$/",
            "replacement" => '$1ouse'
        ],
        // man
        [
            "expression" => "/(m)en$/",
            "replacement" => '$1an'
        ],
        // series
        [
            "expression" => "/(s)eries$/",
            "replacement" => '$1eries'
        ],
        // movies
        [
            "expression" => "/(m)ovies$/",
            "replacement" => '$1ovie'
        ],
        // buses
        [
            "expression" => "/(bus)es$/",
            "replacement" => '$1'
        ],
        // shoes
        [
            "expression" => "/(shoe)s$/",
            "replacement" => '$1'
        ],
        //
        [
            "expression" => "/(o)es$/",
            "replacement" => '$1'
        ],
        // crisis
        [
            "expression" => "/^(cris|ax|test)es$/",
            "replacement" => '$1is'
        ],
        // octopi
        [
            "expression" => "/(octop|vir)i$/",
            "replacement" => '$1us'
        ],
        // aliases
        [
            "expression" => "/(alias|status)es$/",
            "replacement" => '$1'
        ],
        // oxen
        [
            "expression" => "/^(ox)en$/",
            "replacement" => '$1'
        ],
        // matrices
        [
            "expression" => "/(matr)ices$/",
            "replacement" => '$1ix'
        ],
        // feet
        [
            "expression" => "/([a-z]{1})ee([a-z]{1,2})$/",
            "replacement" => '$1oo$2'
        ],
        // fungi
        [
            "expression" => "/([^aeiouy][aeiouy][^aeiouy]{1,2}e*)i|i$/",
            "replacement" => '$1us'
        ],
        // plateaux
        [
            "expression" => "/([^aeiouy])eaux$/",
            "replacement" => '$1eau'
        ],
        //
        [
            "expression" => "/([aeiouy]us)es$/",
            "replacement" => '$1e'
        ],
        //
        [
            "expression" => "/([^l][oa]s)es$/",
            "replacement" => '$1is'
        ],
        // loaves
        [
            "expression" => "/([aeiouy]{2})ves$/",
            "replacement" => '$1f'
        ],
        // lives
        [
            "expression" => "/([aeiouy])ves$/",
            "replacement" => '$1fe'
        ],
        //
        [
            "expression" => "/(h\w{2})ves$/",
            "replacement" => '$1f'
        ],
        // wharves
        [
            "expression" => "/(el|car|cal|war)ves$/",
            "replacement" => '$1f'
        ],
        //
        [
            "expression" => "/([xsz])es$/",
            "replacement" => '$1'
        ],
        // itches twitches arches
        [
            "expression" => "/(x|ch|sh|ss)es$/",
            "replacement" => '$1'
        ],
        [
            "expression" => "/s$/",
            "replacement" => ''
        ]
    ];
}